# Generated by Django 6.0 on 2026-02-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_doctor_hospital_remove_doctor_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
