# Generated by Django 6.0 on 2026-02-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_patient_id_image_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
