# Generated by Django 6.0 on 2026-02-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_image_url_image_image_alter_image_upload_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='patient',
        ),
    ]
