# Generated by Django 6.0 on 2026-02-21 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_image_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='user.patient'),
        ),
        migrations.AlterField(
            model_name='image',
            name='user_notes',
            field=models.CharField(max_length=250),
        ),
    ]
