# Generated by Django 6.0 on 2026-02-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_image_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload_at',
            field=models.DateTimeField(default='2026-02-21 11:28:44.061326+05:30'),
        ),
    ]
