# Generated by Django 6.0 on 2026-02-21 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_image_upload_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
