# Generated by Django 6.0 on 2026-02-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_image_upload_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
