# Generated by Django 6.0 on 2026-02-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_image_upload_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-upload_at']},
        ),
    ]
