# Generated by Django 6.0 on 2026-02-21 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_image_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
